# Generated by Django 5.0.1 on 2024-02-03 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('cat_image', models.ImageField(upload_to='photos/categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
